### PR TITLE
Calculate vertex limits for different vertex layouts

### PR DESCRIPTION
**Pull request by fhsjxk**

### CODE REVIEW

**Comment by alexguirre** [comment]
Where does the 262144 bytes limit for vertex buffers come from? Afaik, the limit was 65535 vertices because the index buffer uses uint16 indices, but I'm not aware of any other limits.

**Comment by fhsjxk** [comment]
because of memory management of game, the maximum size of the vertexdata block should be 256kb

**Comment by ranstar74** [comment]
> because of memory management of game, the maximum size of the vertexdata block should be 256kb

what limit? virtual&physical allocators can handle way larger blocks than this (268 / 1073 mb), during resource building all vertex data goes straight into directx create buffer function without any processing. theres no any other limit im aware of

**Comment by fhsjxk** [comment]
but rockstar does split vertexdata into many parts smaller than 256kb,zmodler3 does the same and saying it's because of memory management.

**Comment by ranstar74** [comment]
thats not game limitation but optimization to make geometry vertex data not taking way too large chunks in resource memory, because resource chunks are power-of-two sized. 
although this limit may be set too low for typical 600k tri vehicle ports, because it will produce much more draw calls

**Pull request closed without merging**
