### PR TITLE
Add unk5c~unk74 names

### PR DESCRIPTION
**Pull request by fhsjxk**

### CODE REVIEW

**Comment by ook3D** [comment]
can you provide any Videos or pictures explaining your changes? not saying they are wrong just want to make sure you tested and confirmed these, although they do seem correct.

**Comment by fhsjxk** [comment]
Yes,I tested these and they are right
In video,I change parknmeter_01,there is value
     <UnkFloat5C value="3000" />
     <UnkFloat60 value="9999" />
     <UnkFloat64 value="0.1" />
     <UnkFloat68 value="9999" />
     <UnkFloat6C value="9999" />
     <UnkFloat70 value="0" />
     <UnkFloat74 value="9999" />

Uploading Grand Theft Auto V 2023.09.23 - 13.05.18.02_.mp4…

**Comment by fhsjxk** [comment]
https://github.com/Skylumz/Sollumz/assets/79156514/43d61635-a763-46e2-853b-1c012a3c7a72

**Comment by fhsjxk** [comment]
[prop_parknmeter_01.yft.txt](https://github.com/Skylumz/Sollumz/files/12705656/prop_parknmeter_01.yft.txt)

**Comment by fhsjxk** [comment]
[fragment.txt](https://github.com/Skylumz/Sollumz/files/12706459/fragment.txt)

**Comment by fhsjxk** [comment]
> can you provide any Videos or pictures explaining your changes? not saying they are wrong just want to make sure you tested and confirmed these, although they do seem correct.

[fragment.txt](https://github.com/Skylumz/Sollumz/files/12706462/fragment.txt)

**Review by alexguirre — APPROVED** [review]

**Comment by fhsjxk** [comment]
UnkFloat78 is Ped Force Scale?

**Pull request merged**
