### PR TITLE
feat(import/asset): added "Import as asset"

### PR DESCRIPTION
**Pull request by XenoS-ITA**
The `Import as asset` option, can be found under the `Geometries` category in the file browser, allows users to import assets (.ydr/.yft) that are already YTYP-ready, automatically joining geometries since the purpose is to prop maps.
It also sets imported props as assets so that the `asset browser` can be used

### CODE REVIEW

**Comment by CFox04** [comment]
There is a ton of copy and pasted code here and a lot of it is unnecessary. All you need to do is call ``obj.mark_asset()`` after import if the setting is enabled.

**Comment by CFox04** [comment]
Guess I was wrong about running ``obj.mark_asset()`` at the end since you can't make hierarchies assets, but still need to refactor to avoid repeated code.

**Comment by XenoS-ITA** [comment]
i had decided to create separate functions since i would have to remove 90% of the original function and i noticed that for example the `drawable_to_obj` function is also called by the yft and probably by something else, creating several problems. 
otherwise it is the first time i write blender plugins so if you want to give me some advices is welcome

**Comment by Yam-Ka** [comment]
Or just use my add-on 🤣😂
https://github.com/Yam-Ka/Eazy_Azzets

**Comment by XenoS-ITA** [comment]
thanks for sharing your add-on. however, that is a plugin that is not integrated directly into Sollumz. 
anyway i tried installing it but doesnt show up in the addons menu.

**Comment by CFox04** [comment]
Implemented in 8d6023f02f6f33dc5205d322f12563bdde90a72e

**Pull request closed without merging**
