### PR TITLE
Octants generation algorithm from companion

### PR DESCRIPTION
**Pull request by emcifuntik**

### CODE REVIEW

**Comment by emcifuntik** [comment]
> Does this result in the same octant calculation as the original file? Someone tested this and showed me that they had different results from the original file. I can test this soon.
> 
> Most yfts work even without octants, we're not entirely sure where octants are used or cause issues, so it's hard to test if they are calculated correctly. The best thing to do is just compare it to the original files.

Yes, calculation is the same as in game engine. All vehicle yfts have octants and destroyable yfts too

**Comment by coltfox** [comment]
> > Does this result in the same octant calculation as the original file? Someone tested this and showed me that they had different results from the original file. I can test this soon.
> 
> > 
> 
> > Most yfts work even without octants, we're not entirely sure where octants are used or cause issues, so it's hard to test if they are calculated correctly. The best thing to do is just compare it to the original files.
> 
> 
> 
> Yes, calculation is the same as in game engine. All vehicle yfts have octants and destroyable yfts too

Awesome, can't wait to test! In the meantime can you make sure the code style matches pep8? Use this style for variable and function names: my_variable

**Comment by coltfox** [comment]
I just tested this and, for me, these calculations don't match up with the original files.

**prop_streetlight_01b.yft**
image
Sollumz-exported on the left and original file on the right.

Also, can you explain what the algorithm is doing exactly? I'm having trouble understanding it.

**Comment by emcifuntik** [comment]
> I just tested this and, for me, these calculations don't match up with the original files.
> 
> **prop_streetlight_01b.yft** image Sollumz-exported on the left and original file on the right.
> 
> Also, can you explain what the algorithm is doing exactly? I'm having trouble understanding it.

Worked fine on another one prop. I will try to fix later

**Comment by vadzz-dev** [comment]
Oh it seems they run it on vertices_2

**Comment by vadzz-dev** [comment]
Might actually try to reproduce shrink algorythm that generates vertices_2

**Comment by emcifuntik** [comment]
You can try now

**Comment by coltfox** [comment]
> You can try now

Ok, I will as soon as I get to my PC.

**Comment by coltfox** [comment]
> Might actually try to reproduce shrink algorythm that generates vertices_2 later

We've always thought that vertices_2 is a "damaged" state for bound geometries and that it should be defined by the artist. Are you saying that this is actually generated instead? If so, what would be the purpose of storing a set of shrinked vertices?

**Comment by vadzz-dev** [comment]
> > Might actually try to reproduce shrink algorythm that generates vertices_2 later
> 
> We've always thought that vertices_2 is a "damaged" state for bound geometries and that it should be defined by the artist. Are you saying that this is actually generated instead? If so, what would be the purpose of storing a set of shrinked vertices?

They seem to be shrinked along normals by 0.04 but not 100% sure it’s always gemerated

I think the purpose is the same as octants prob just not to spend time for calculations while loading the model but again not sure about this

**Comment by coltfox** [comment]
After some talking in the Codewalker discord, we are pretty sure that Vertices2 is Vertices shrunk down by the margin. Someone mentioned this function from Companion ``rage::phBoundGeometry::SetMarginAndShrink``.

As for the PR, this will not work because Sollumz does not currently export vertices_2. Also, I tried passing in a hardcoded vertices_2 list, and the octants output is still incorrect. Make sure to test on ``prop_streetlight_01b.yft``.

So now that we know that vertices2 and octants can be automatically generated, we are just going to try and implement it in Codewalker and exclude the Vertices2 and Octants from the XML. If you want to talk more feel free to [join the Sollumz discord](https://discord.gg/spv48vyW) and ping @colton.

**Pull request closed without merging**
